/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultIndexRouteImport } from './routes/result/index'
import { Route as PhotoIndexRouteImport } from './routes/photo/index'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as AddressIndexRouteImport } from './routes/address/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIndexRoute = ResultIndexRouteImport.update({
  id: '/result/',
  path: '/result/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoIndexRoute = PhotoIndexRouteImport.update({
  id: '/photo/',
  path: '/photo/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressIndexRoute = AddressIndexRouteImport.update({
  id: '/address/',
  path: '/address/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/address/': typeof AddressIndexRoute
  '/map/': typeof MapIndexRoute
  '/photo/': typeof PhotoIndexRoute
  '/result/': typeof ResultIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/address': typeof AddressIndexRoute
  '/map': typeof MapIndexRoute
  '/photo': typeof PhotoIndexRoute
  '/result': typeof ResultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/address/': typeof AddressIndexRoute
  '/map/': typeof MapIndexRoute
  '/photo/': typeof PhotoIndexRoute
  '/result/': typeof ResultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/address/' | '/map/' | '/photo/' | '/result/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/address' | '/map' | '/photo' | '/result'
  id: '__root__' | '/' | '/address/' | '/map/' | '/photo/' | '/result/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressIndexRoute: typeof AddressIndexRoute
  MapIndexRoute: typeof MapIndexRoute
  PhotoIndexRoute: typeof PhotoIndexRoute
  ResultIndexRoute: typeof ResultIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/': {
      id: '/result/'
      path: '/result'
      fullPath: '/result/'
      preLoaderRoute: typeof ResultIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/': {
      id: '/photo/'
      path: '/photo'
      fullPath: '/photo/'
      preLoaderRoute: typeof PhotoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address/': {
      id: '/address/'
      path: '/address'
      fullPath: '/address/'
      preLoaderRoute: typeof AddressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressIndexRoute: AddressIndexRoute,
  MapIndexRoute: MapIndexRoute,
  PhotoIndexRoute: PhotoIndexRoute,
  ResultIndexRoute: ResultIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
